<a href="https://colab.research.google.com/github/junheeyoon/Big-Data-analyst-Study/blob/master/ML_Scikit_learn_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 읽기

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# 현재 경로 확인
import os
print(os.path.abspath(os.curdir))

# Root 경로 설정
import os
os.chdir('/content/drive/MyDrive/데이터분석')

/content


1) 데이터 읽기

In [3]:
import pandas as pd
path_to_data = './data/Titanic/train.csv'
df = pd.read_csv(path_to_data, encoding='cp949')

# DataFrame type 확인
df.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

##1. Scikit-learn 과제
  - 타이타닉 데이터 이용
  - 생존 확률을 Scikit-learn 의 logistic regression 을 이용하여 학습 & 모델을 만들 것

###Survived 에 상관관계가 높은 2개의 feature(Sex, Pclass)를 가지고 모델을 만들었습니다.

In [4]:
#문자열을 숫자로 변환
df['Sex'] = df['Sex'].map({'female':1,'male':0})

In [5]:
#feature 분리하기
df['FirstClass'] = df['Pclass'].apply(lambda x: 1 if x == 1 else 0)
df['SecondClass'] = df['Pclass'].apply(lambda x: 1 if x == 2 else 0)
df['ThirdClass'] = df['Pclass'].apply(lambda x: 1 if x == 3 else 0)

In [6]:
features = df[['Sex', 'FirstClass', 'SecondClass', 'ThirdClass']]
#features = df[['Sex']]
survival = df['Survived']

In [7]:
#학습세트/평가세트 분리하기
from sklearn.model_selection import train_test_split

X_train, X_text, y_train, y_test = train_test_split(features, survival)

In [10]:
#데이터 정규화(스케일링) 하기
#로지스틱 회귀는 실행할 때 regularation을 사용하기 때문에 데이터를 스케일링하는 작업이 필요하다.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_text = scaler.transform(X_text)

In [11]:
#LogisticRegression model 생성
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [12]:
print(model.score(X_train, y_train))

0.7934131736526946


In [14]:
model.predict(X_text)

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0])

In [ ]:
print(model.score(test_features, test_labels))

0.8026905829596412


In [15]:
#각 feature들의 계수
print(model.coef_)

[[ 1.26390724  0.38300057  0.04240368 -0.36407103]]


###예측하기

In [ ]:
import numpy as np
A = np.array([0.0])
B = np.array([1.0])
#A = np.array([0.0, 1.0, 0.0, 0.0])
#B = np.array([1.0, 0.0, 1.0, 0.0])
#C = np.array([0.0, 0.0, 0.0, 1.0])
sample_passengers = np.array([A, B])
sample_passengers = scaler.transform(sample_passengers)
print(model.predict(sample_passengers))
print(model.predict_proba(sample_passengers))

[0 1]
[[0.80563073 0.19436927]
 [0.2684574  0.7315426 ]]
