<a href="https://colab.research.google.com/github/junheeyoon/Big-Data-analyst-Study/blob/master/Python_%EA%B8%B0%EC%B4%88%EC%A0%95%EB%A6%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python 기초정리

In [1]:

# 워킹 디렉토리 확인 
import os 
os.getcwd()

'/content'

In [3]:
import pandas as pd

In [5]:
# 객체 속성 및 메소드 정보 확인
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_ty

In [6]:
# 함수 사용법 확인
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __ceil__(...)
 |      Ceiling of

In [7]:
# 도움말 찾기
a = 'string' # a라는 변수에 string을 입력
dir(a) # a라는(문자열) 변수에 쓸 수 있는 method 조회

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


#기본 분석 환경 세팅

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

CSV, TSV, TXT : pandas read_csv

In [ ]:
# csv read
pd.read_csv('경로/파일이름.csv', encoding = 'cp949') 
## Parameters
# header = True  : 변수명 있을 시 불러옴
# names = [ , , , , ] : 변수명 직접 추가
# encoding : utf-8, cp949, euc-kr
# sep = ','
# 경우에 따라 engine = 'python'
# skipinitialspace = True : 구분자 양쪽 공백 제거

# tsv read
pd.read_csv("train.tsv", delimiter='\t')

# csv write
df.to_csv('./data/df.csv', header = True, index = False, encoding = 'cp949')

numpy

In [10]:
# array 생성 
a = np.array([1,2,3,4])

# array 생성의 여러 예
b = np.zeros((3,3)) ; print('b', b)
c = np.ones((3,4)) ; print('c', c)
d = np.full((2,2),7) ; print('d',d) # 특별 값으로 채우기
e = np.eye(3,3) ; print('e',e) # 단위행렬
f = np.random.random((2,2)) ; print('f',f) # 랜덤
g = np.arange(5) ; print('g', g)

b [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
c [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d [[7 7]
 [7 7]]
e [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
f [[0.77025763 0.66404869]
 [0.62519116 0.5729433 ]]
g [0 1 2 3 4]


reshape

In [16]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]]) ; print('a',a) # array 생성
a = a.reshape(3,2) ; print('a', a) # reshape
a = a.reshape(6,-1) ; print('a', a)
a = a.reshape(6,1) ; print('a', a)

a [[1 2 3]
 [4 5 6]]
a [[1 2]
 [3 4]
 [5 6]]
a [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
a [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


slice

In [17]:
print( d[0,:] ) # 정수 슬라이싱 --> 배열 차원 감소
print( d[0:1,:] ) # 그냥 슬라이싱 --> 배열 차원 유지
d.copy() # 배열 복사

[7 7]
[[7 7]]


array([[7, 7],
       [7, 7]])

숫자 다루기

In [21]:

import math
a = np.array([math.e,2,3]) # math.e 는 자연상수
print(a)
print(np.abs(a)) # 절대값
print(np.sqrt(a)) # 제곱근
print(np.log(a)) # 로그
print(np.floor(a)) # 내림
print(np.ceil(a)) # 올림
print(np.rint(a)) # 반올림

[2.71828183 2.         3.        ]
[2.71828183 2.         3.        ]
[1.64872127 1.41421356 1.73205081]
[1.         0.69314718 1.09861229]
[2. 2. 3.]
[3. 2. 3.]
[3. 2. 3.]


#Pandas DataFrame

In [63]:
# Dataframe 만드는 법
# np.nan으로 NaN 값도 넣을 수 있음
data = {'name': ['Jason', 'Molly', np.nan, 'Jake', 'Amy'], 
        'year': [2012, 2012, 2013, 2014, 2014], 
        'reports': [4, 24, 31, np.nan, 3]}
df = pd.DataFrame(data, index = ['Cochice', 'Pima', 'Santa Cruz', 'Maricopa', 'Yuma'])
df

name  year  reports
Cochice     Jason  2012      4.0
Pima        Molly  2012     24.0
Santa Cruz    NaN  2013     31.0
Maricopa     Jake  2014      NaN
Yuma          Amy  2014      3.0

DataFrame 컬럼명 변경

In [23]:
df.rename(columns={'name': 'full_name'})

full_name  year  reports
Cochice        Jason  2012        4
Pima           Molly  2012       24
Santa Cruz       NaN  2013       31
Maricopa        Jake  2014        2
Yuma             Amy  2014        3

In [29]:
# df 
df.head()
df.tail()
df.shape
df.columns
df.dtypes 
df.info()
df.describe() 

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Cochice to Yuma
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   name     4 non-null      object
 1   year     5 non-null      int64 
 2   reports  5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 320.0+ bytes


year    reports
count     5.0   5.000000
mean   2013.0  12.800000
std       1.0  13.663821
min    2012.0   2.000000
25%    2012.0   3.000000
50%    2013.0   4.000000
75%    2014.0  24.000000
max    2014.0  31.000000

Dict, array

In [38]:
# dictionary 
d = {"a" : 1, "b":2}
d.keys()
d.values()
d.items()
# array 
a.shape
a.dtype

dtype('float64')

결측치 처리

In [40]:
# na 처리 : dropna(), fillna()
df.dropna() # nan이 하나라도 들어간 행은 삭제
df.dropna(how = 'all') # 데이터가 모두 nan인 행만 삭제 / 초기값:'any'

name  year  reports
Cochice     Jason  2012        4
Pima        Molly  2012       24
Santa Cruz    NaN  2013       31
Maricopa     Jake  2014        2
Yuma          Amy  2014        3

In [54]:
## Parameters
# axis = 'index' / 'columns'
# subset = ['col1', 'col2', ...] # 적용 대상 컬럼 특정

df.fillna(0) # na를 0으로 채우기

name  year  reports
Cochice     Jason  2012        4
Pima        Molly  2012       24
Santa Cruz      0  2013       31
Maricopa     Jake  2014        2
Yuma          Amy  2014        3

In [79]:
new_data = {'name': 'null', 'year':9999, 'reports':0}
df.fillna(new_data) # na 발생 시 a 열에는 0, b 열에는 1, c 열에는 -999로 채움
df.fillna(new_data, limit = 2) # 각 열별로 2개의 nan까지 대체
df.fillna(method = 'ffill') # 열 별로 바로 앞의 데이터로 채움
df = df.fillna(method = 'bfill') # 열 별로 바로 뒤의 데이터로 채움
# ffill의 경우 첫 행이거나, 앞의 데이터가 nan일 경우 nan유지. bfill도 반대로 동일

In [71]:
# 평균값, 중앙값으로 대치
df.loc['Maricopa','reports'] = np.nan # 평균값으로 
#df.loc['Maricopa','reports'] = df['reports'].mean() # 평균값으로 
df.loc['Maricopa','reports'] = df['reports'].median() # 중앙값으로

In [72]:
df

name  year reports
Cochice     Jason  2012       4
Pima        Molly  2012      24
Santa Cruz    NaN  2013      31
Maricopa     Jake  2014      14
Yuma          Amy  2014       3

중복제거

In [80]:
# DataFrame 중복 row 제거
df.duplicated() # 중복 여부 boolean 형태로 반환

Cochice       False
Pima          False
Santa Cruz    False
Maricopa      False
Yuma          False
dtype: bool

In [81]:
df.drop_duplicates() # 행 내용이 동일한 경우 제거

name  year  reports
Cochice     Jason  2012      4.0
Pima        Molly  2012     24.0
Santa Cruz   Jake  2013     31.0
Maricopa     Jake  2014     14.0
Yuma          Amy  2014      3.0

In [82]:
df.drop_duplicates(['name'], keep='last') # col1기준 중복값중 마지막만 남겨둠

name  year  reports
Cochice   Jason  2012      4.0
Pima      Molly  2012     24.0
Maricopa   Jake  2014     14.0
Yuma        Amy  2014      3.0

데이터 조회하기

In [84]:
# 고유값 조회
df['year'].unique()

array([2012, 2013, 2014])

In [86]:
print(len(df['year'].unique()))

3


In [93]:
# 행기준 : iloc 사용
#df.iloc[:,2]
# 행번호 1~2 조회
df.iloc[1:3,1:3]

year  reports
Pima        2012     24.0
Santa Cruz  2013     31.0